/* =====================================================================
   MINE AUX TRÉSORS — TEXTES EN ANGLAIS
   ---------------------------------------------------------------------
   Quand le joueur choisit « English » dans les Paramètres, chaque texte
   français (à gauche) est remplacé par sa version anglaise (à droite).

   Quelques règles :
   - Ne change que le texte de DROITE (l'anglais).
   - Si tu modifies un texte français dans config.js (un nom de trésor,
     un tutoriel…), modifie aussi la ligne de gauche ici, sinon le jeu
     affichera le texte en français même en anglais.
   - Les {n}, {x}, {a}… sont remplacés par un nombre ou un nom :
     garde-les tels quels dans la traduction.
   - Garde les guillemets " " et la virgule à la fin de chaque ligne.
   ===================================================================== */
window.TEXTES_EN = {

  /* ---------- Titre, village, bâtiments ---------- */
  "Mine aux Trésors": "Treasure Mine",
  "Mine": "Mine",
  "Musée": "Museum",
  "Boutique": "Shop",
  "Forge": "Forge",
  "Atelier": "Workshop",
  "Améliorations": "Upgrades",
  "Articles": "Items",
  "Nouveau": "New",
  "Nouveau !": "New!",
  "Fais glisser pour te déplacer dans le village": "Drag to move around the village",
  "Objectifs": "Goals",
  "La mine": "The mine",
  "Descendre": "Go down",
  "Descendre dans la mine": "Go down into the mine",
  "Entrée de la mine": "Mine entrance",
  "‹ Village": "‹ Village",
  "Record : niveau {n}": "Record: level {n}",
  "{n} checkpoint": "{n} checkpoint",
  "{n} checkpoints": "{n} checkpoints",
  "{a} / {b} trésors": "{a} / {b} treasures",
  "{n} géode": "{n} geode",
  "{n} géodes": "{n} geodes",
  "Aucune géode": "No geodes",
  "Pièces": "Coins",
  "pièces": "coins",
  "énergie": "energy",

  /* ---------- Paramètres ---------- */
  "Paramètres": "Settings",
  "Son": "Sound",
  "Musique": "Music",
  "Cheats": "Cheats",
  "Cheats débloqués": "Cheats unlocked",
  "Langue": "Language",
  "Français": "Français",
  "English": "English",
  "Comment jouer": "How to play",
  "Recommencer la partie": "Restart the game",
  "Confirmer : tout effacer ?": "Confirm: erase everything?",
  "Nouvelle partie !": "New game!",
  "Fermer": "Close",

  /* ---------- Objectifs ---------- */
  "Récupérer {n} pièces": "Collect {n} coins",
  "Objectif réussi : +{n} pièces !": "Goal complete: +{n} coins!",

  /* ---------- Mine : écran ---------- */
  "Niveau": "Level",
  "Niveau spécial": "Special level",
  "Niveau {n} ↓": "Level {n} ↓",
  "Niveau suivant ↓": "Next level ↓",
  "Mine suivante ↓": "Next mine ↓",
  "Énergie": "Energy",
  "Énergie pleine": "Energy full",
  "+1 dans {s} s": "+1 in {s} s",
  "Recharge au village": "Refills at the village",
  "Remonter au village": "Back to the village",
  "Trésors": "Treasures",
  "Trésors à trouver": "Treasures to find",
  "0 / 0 trouvés": "0 / 0 found",
  "{f} / {n} dégagés": "{f} / {n} uncovered",
  "Ouvrir le sac": "Open the bag",
  "Sac 0/4": "Bag 0/4",
  "Sac {n}/{cap}": "Bag {n}/{cap}",
  "Outils": "Tools",
  "Pelle": "Shovel",
  "Gratuite": "Free",
  "Pioche": "Pickaxe",
  "/ coup": "/ hit",
  "Arrosoir": "Watering can",
  "Prêt": "Ready",
  "Prêt ×{n}": "Ready ×{n}",
  "Remplissage {s} s": "Refilling {s} s",
  "Touche une case pour poser la bombe": "Tap a cell to place the bomb",
  "Annuler": "Cancel",
  "Gemme": "Gem",
  "Géode": "Geode",
  "Artefact": "Artefact",
  "{x} cachée": "Hidden {x}",
  "{x} (laissé)": "{x} (left behind)",

  /* ---------- Mine : messages ---------- */
  "Attention, c'est brûlant ! Refroidis le magma avec l'arrosoir.": "Careful, it's burning hot! Cool the magma with the watering can.",
  "Racine trop dure pour la pelle : casse sa souche à la pioche !": "This root is too tough for the shovel: break its stump with the pickaxe!",
  "La glace ne fond à la pelle que si elle touche du magma.": "Ice only melts with the shovel when it touches magma.",
  "La pelle ne passe pas la roche. Prends la pioche.": "The shovel can't get through rock. Take the pickaxe.",
  "La terre part à la pelle, et c'est gratuit !": "Dirt comes off with the shovel, and it's free!",
  "Trop chaud ! Arrose le magma pour le refroidir d'abord.": "Too hot! Water the magma to cool it first.",
  "Plus d'énergie ! +1 dans {s} s, ou bois une potion.": "Out of energy! +1 in {s} s, or drink a potion.",
  "Plus d'énergie ! Bois une potion ou remonte au village pour recharger.": "Out of energy! Drink a potion or go back to the village to refill.",
  "Plus de bombes ! Achètes-en à la boutique du village.": "No bombs left! Buy some at the village shop.",
  "Déjà refroidi : casse-le à la pioche.": "Already cooled: break it with the pickaxe.",
  "L'arrosoir sert à refroidir le magma.": "The watering can is for cooling magma.",
  "L'arrosoir se remplit… encore {s} s": "The watering can is refilling… {s} s left",
  "Chaîne ×{n} !": "Chain ×{n}!",
  "+{n} pièces": "+{n} coins",
  "+1 potion": "+1 potion",
  "+{n} potion": "+{n} potion",
  "+{n} potions": "+{n} potions",
  "Éclat !": "Shatter!",
  "Explosion de gaz !": "Gas explosion!",
  "La bombe ne vient pas à bout du magma chaud : arrose-le d'abord.": "Bombs can't clear hot magma: water it first.",
  "Il faut les {need} Clés du Roi Mineur pour ouvrir ce coffre (tu en as {got}). C'est un bonus : tu peux continuer sans !": "You need the {need} Miner King's Keys to open this chest (you have {got}). It's a bonus: you can carry on without it!",
  "Gardien vaincu !": "Guardian defeated!",
  "(à l'Atelier)": "(at the Workshop)",
  "Checkpoint niveau {n} débloqué !": "Checkpoint level {n} unlocked!",
  "⛺ Camp de biome débloqué (niveau {n}) !": "⛺ Biome camp unlocked (level {n})!",

  /* ---------- Descendre ---------- */
  "Sac plein, peu d'énergie": "Full bag, low energy",
  "Sac plein": "Full bag",
  "Peu d'énergie": "Low energy",
  "Attention, ton sac est plein et il te reste peu d'énergie.": "Careful, your bag is full and you're low on energy.",
  "Attention, ton sac est plein : tu ne pourras plus récupérer de trésors.": "Careful, your bag is full: you won't be able to pick up more treasures.",
  "Attention, il te reste peu d'énergie : remonte au village pour recharger.": "Careful, you're low on energy: go back to the village to recharge.",
  "Attention, il te reste peu d'énergie.": "Careful, you're low on energy.",
  "Remonter": "Go back up",
  "Descendre quand même": "Go down anyway",
  "Rester ici": "Stay here",

  /* ---------- Sac ---------- */
  "Mon sac": "My bag",
  "Consommables": "Consumables",
  "Retour à la mine": "Back to the mine",
  "{n} / {cap} cases utilisées": "{n} / {cap} slots used",
  "{n} place libre": "{n} free slot",
  "{n} places libres": "{n} free slots",
  "sac plein": "bag full",
  "Ton sac est vide pour l'instant.": "Your bag is empty for now.",
  "Minerais récoltés (hors sac) :": "Ores gathered (outside the bag):",
  "Utiliser": "Use",
  "Aucun consommable pour l'instant.": "No consumables yet.",
  "Nouvelle découverte !": "New discovery!",
  "Trésor trouvé": "Treasure found",
  "Ton sac est plein ({n} cases). Laisse un doublon de ton sac pour prendre cette nouvelle découverte ?": "Your bag is full ({n} slots). Leave a duplicate from your bag to take this new discovery?",
  "Ton sac est plein ({n} cases). Laisse un objet de ton sac pour prendre cette nouvelle découverte ?": "Your bag is full ({n} slots). Leave an item from your bag to take this new discovery?",
  "Laisser {x}": "Leave {x}",
  "doublon · et prendre le nouveau": "duplicate · and take the new one",
  "objet le moins précieux · et prendre le nouveau": "least valuable item · and take the new one",
  "Laisser la découverte": "Leave the discovery",
  "{x} laissé dans la mine": "{x} left in the mine",

  /* ---------- Consommables (sac et boutique) ---------- */
  "Bombe": "Bomb",
  "Fait sauter les 9 cases autour de la case touchée.": "Blows up the 9 cells around the cell you tap.",
  "Fait sauter les 9 cases autour de la cible.": "Blows up the 9 cells around the target.",
  "Radar": "Radar",
  "Entoure l'emplacement d'un trésor caché.": "Circles where a hidden treasure lies.",
  "Potion d'énergie": "Energy potion",
  "Remplit ton énergie au maximum.": "Fills your energy to the max.",
  "Pas de radar. Achètes-en à la boutique du village.": "No radar. Buy some at the village shop.",
  "Tous les trésors restants sont déjà repérés.": "All remaining treasures are already spotted.",
  "Radar : artefact repéré !": "Radar: artefact spotted!",
  "Radar : géode repérée !": "Radar: geode spotted!",
  "Pas de potion. Achètes-en à la boutique du village.": "No potion. Buy some at the village shop.",
  "Ton énergie est déjà pleine.": "Your energy is already full.",
  "Énergie rechargée !": "Energy refilled!",

  /* ---------- Boutique ---------- */
  "De l'équipement et des consommables pour tes descentes, payés en pièces.": "Gear and consumables for your trips down, paid in coins.",
  "Agrandir le sac": "Bigger bag",
  "{a} → {b} cases": "{a} → {b} slots",
  "{a} cases": "{a} slots",
  "Agrandir": "Upgrade",
  "Acheter": "Buy",
  "Sac agrandi : {n} cases !": "Bag upgraded: {n} slots!",

  /* ---------- Forge ---------- */
  "Améliore tes outils avec tes minerais et quelques pièces. Les améliorations sont permanentes.": "Improve your tools with your ores and a few coins. Upgrades are permanent.",
  "Réserve d'énergie": "Energy reserve",
  "Énergie max {a} → {b}": "Max energy {a} → {b}",
  "Énergie max {a}": "Max energy {a}",
  "Pioche renforcée": "Stronger pickaxe",
  "{a} → {b} dégâts par coup": "{a} → {b} damage per hit",
  "{a} dégâts par coup": "{a} damage per hit",
  "Coup en éclats": "Shattering blow",
  "Chance de casser aussi une roche voisine : {a} → {b}": "Chance to also break a nearby rock: {a} → {b}",
  "{a} de chance de casser une roche voisine": "{a} chance to break a nearby rock",
  "Arrosoir rapide": "Fast watering can",
  "Recharge {a} s → {b} s": "Refill {a} s → {b} s",
  "Recharge en {a} s": "Refills in {a} s",
  "Grand arrosoir": "Big watering can",
  "{a} → {b} arrosages avant de recharger": "{a} → {b} waterings before refilling",
  "{a} arrosages avant de recharger": "{a} waterings before refilling",
  "Un nouveau niveau se débloque plus profond": "A new level unlocks deeper down",
  "pour l'instant": "for now",
  "Forger": "Forge",
  "{x} : niveau {n} !": "{x}: level {n}!",

  /* ---------- Ascenseur ---------- */
  "Ascenseur": "Lift",
  "Choisis d'abord un biome. Ton record : niveau {n}.": "First choose a biome. Your record: level {n}.",
  "Choisis ton niveau de départ. Ton record : niveau {n}.": "Choose your starting level. Your record: level {n}.",
  "Niveaux {a}–{b}": "Levels {a}–{b}",
  "Niveau {n}": "Level {n}",
  "Descendre au niveau {n}": "Go down to level {n}",
  "Camp de biome": "Biome camp",
  "En cours": "In progress",
  "← Choisir un autre biome": "← Choose another biome",
  "Biome {n}": "Biome {n}",

  /* ---------- Retour à la surface ---------- */
  "Retour à la surface": "Back to the surface",
  "Fin de l'expédition": "End of expedition",
  "Niveau atteint : {n}": "Level reached: {n}",
  "Nouveau checkpoint !": "New checkpoint!",
  "Ouvrir les géodes": "Open geodes",
  "Minerais": "Ores",
  "Géodes": "Geodes",
  "Ton butin du niveau {n}": "Your loot from level {n}",
  "Tu remontes les mains vides cette fois. Ton niveau t'attend !": "You're coming back empty-handed this time. Your level is waiting for you!",
  "Ouvrir mes géodes à l'atelier": "Open my geodes at the workshop",
  "Aller au village": "Go to the village",
  "Vendu": "Sold",
  "Doublon": "Duplicate",
  "À ouvrir à l'atelier": "To open at the workshop",
  "Ajouté à ta collection": "Added to your collection",
  "{x} : nouvelle étoile !": "{x}: new star!",
  "Prime à récupérer au Musée": "Bonus to collect at the Museum",
  "{x} réunies !": "{x} complete!",
  "Aucun minerai récolté pour l'instant.": "No ores gathered yet.",

  /* ---------- Musée ---------- */
  "{a} trésors sur {b} sont exposés. Chaque nouveau trésor rapporte une prime, les doublons sont vendus à leur valeur. Complète une collection pour gagner une étoile : chaque étoile augmente le prix de revente de ses doublons.": "{a} of {b} treasures are on display. Each new treasure earns a bonus, duplicates are sold for their value. Complete a collection to earn a star: each star raises the resale price of its duplicates.",
  "Gemmes": "Gems",
  "Artefacts": "Artefacts",
  "{x} : +{n} pièces !": "{x}: +{n} coins!",
  "Prix de vente d'un doublon": "Resale price of a duplicate",
  "trouvé ×{n}": "found ×{n}",
  "Prochaine étoile : encore {n} objet": "Next star: {n} more item",
  "Prochaine étoile : encore {n} objets": "Next star: {n} more items",
  "prime {n} pièces": "bonus {n} coins",
  "Toutes les étoiles obtenues !": "All stars earned!",
  "Dans les géodes": "Inside geodes",
  "Où :": "Where:",
  "dès le niveau {a}": "from level {a}",
  "niveaux {a} à {b}": "levels {a} to {b}",
  "niveau {a}": "level {a}",
  "dans la terre": "in the dirt",
  "sous la pierre": "under stone",
  "sous la pierre dure": "under hard stone",
  "sous le magma": "under magma",
  "dans les coffres bonus": "in bonus chests",
  "Nouvelle étoile !": "New star!",
  "Nouvelles étoiles !": "New stars!",
  "Récupérer": "Collect",
  "doublons +{n} %": "duplicates +{n}%",
  "{n} étoile sur {max}": "{n} star out of {max}",
  "{n} étoiles sur {max}": "{n} stars out of {max}",
  "{n} collection restante à découvrir": "{n} collection left to discover",
  "{n} collections restantes à découvrir": "{n} collections left to discover",

  /* ---------- Atelier ---------- */
  "Frapper": "Strike",
  "Aucune géode à ouvrir. Trouve-en dans la mine !": "No geodes to open. Find some in the mine!",
  "Ouvrir : {x}": "Open: {x}",
  "Géode {r}, résistance {n} sur 4": "{r} geode, toughness {n} out of 4",
  "Si tu perds tes {n} cœurs, la géode s'ouvre quand même, mais donne une gemme {a} au lieu de {b}.": "If you lose your {n} hearts, the geode still opens, but gives a {a} gem instead of {b}.",
  "Si tu perds tes {n} cœurs, la géode blanche s'effrite et ne donne que <b>{c} pièces</b>.": "If you lose your {n} hearts, the white geode crumbles and only gives <b>{c} coins</b>.",
  "Coups": "Hits",
  "{a} coup(s) réussi(s) sur {b}": "{a} successful hit(s) out of {b}",
  "{x} : {gem} !": "{x}: {gem}!",
  "Plus de cœurs : la {x} s'ouvre quand même, mais donne {gem}.": "Out of hearts: the {x} still opens, but gives {gem}.",
  "Plus de cœurs : la géode blanche s'effrite. Tu récupères {n} pièces.": "Out of hearts: the white geode crumbles. You get {n} coins.",
  "Géode ouverte !": "Geode opened!",
  "Raté…": "Missed…",
  "Géode suivante": "Next geode",
  "Retour au village": "Back to the village",

  /* ---------- Fin de la mine ---------- */
  "Mine 2 : bientôt disponible": "Mine 2: coming soon",
  "Bravo, tu as atteint le fond de la mine ! Une nouvelle mine t'attend… elle arrive bientôt.": "Well done, you reached the bottom of the mine! A new mine awaits you… coming soon.",

  /* ---------- Comment jouer ---------- */
  "<b>Pelle</b> : maintiens et glisse sur la terre pour la retirer. Elle ne coûte rien.": "<b>Shovel</b>: hold and swipe over dirt to clear it. It costs nothing.",
  "<b>Pioche</b> : touche la pierre pour la casser. Chaque coup coûte 1 énergie : pierre 3 coups, minerai 3, magma refroidi 5.": "<b>Pickaxe</b>: tap stone to break it. Each hit costs 1 energy: stone 3 hits, ore 3, cooled magma 5.",
  "<b>Arrosoir</b> : refroidit le magma. Il lui faut quelques secondes pour se remplir.": "<b>Watering can</b>: cools magma. It needs a few seconds to refill.",
  "<b>Bombe</b> : dans ton sac, onglet Consommables. Elle fait sauter les 9 cases autour de la cible, sauf le magma chaud.": "<b>Bomb</b>: in your bag, Consumables tab. It blows up the 9 cells around the target, except hot magma.",
  "<b>Radar</b> : dans ton sac, onglet Consommables. Il entoure l'emplacement d'un trésor caché.": "<b>Radar</b>: in your bag, Consumables tab. It circles where a hidden treasure lies.",
  "<b>Sac</b> : chaque trésor et chaque géode prend une case (les minerais ne comptent pas). Agrandis-le à la boutique.": "<b>Bag</b>: each treasure and each geode takes one slot (ores don't count). Make it bigger at the shop.",
  "<b>Ascenseur</b> : au village, « Descendre » te propose les checkpoints débloqués (niveau 10, 20, 30…), rangés par biome. C'est gratuit.": "<b>Lift</b>: in the village, “Go down” offers the checkpoints you unlocked (level 10, 20, 30…), sorted by biome. It's free.",
  "<b>Remonter</b> : quitte la mine quand tu veux. Ton sac se vide : les nouveaux trésors vont au musée, les doublons sont vendus.": "<b>Go back up</b>: leave the mine whenever you want. Your bag is emptied: new treasures go to the museum, duplicates are sold.",
  "<b>Musée</b> : chaque nouveau trésor rapporte une prime. Complète une collection pour gagner une étoile (jusqu'à {n}) : ses doublons se vendent plus cher, et la prime se récupère au Musée.": "<b>Museum</b>: each new treasure earns a bonus. Complete a collection to earn a star (up to {n}): its duplicates sell for more, and the bonus is collected at the Museum.",
  "<b>Boutique</b> : agrandis ton sac. D'autres articles arrivent plus profond.": "<b>Shop</b>: make your bag bigger. More items arrive deeper down.",
  "<b>Forge</b> : améliore tes outils avec du fer, du cuivre, de l'or et des pièces.": "<b>Forge</b>: improve your tools with iron, copper, gold and coins.",
  "<b>Pierre dure</b> : il faut deux fois plus de coups de pioche.": "<b>Hard stone</b>: takes twice as many pickaxe hits.",
  "<b>Source</b> : creuse-la à la pelle, son eau refroidit le magma collé à elle.": "<b>Spring</b>: dig it with the shovel, its water cools the magma touching it.",
  "<b>Magma en chaîne</b> : arrose une case, tout le magma collé refroidit.": "<b>Chain magma</b>: water one cell and all the connected magma cools down.",
  "<b>Case mystère</b> : toujours un cadeau (pièces, minerai, potion ou géode).": "<b>Mystery cell</b>: always a gift (coins, ore, potion or geode).",
  "<b>Racines</b> : casse la souche, toutes ses racines disparaissent.": "<b>Roots</b>: break the stump and all its roots disappear.",
  "<b>Glace</b> : la pioche y fait moitié moins de dégâts. Collée au magma, elle fond d'un coup de pelle. Une bombe la fait fondre aussi.": "<b>Ice</b>: the pickaxe does half damage on it. Next to magma, it melts with one stroke of the shovel. A bomb melts it too.",
  "<b>Gaz</b> : une bombe qui le touche fait une explosion 5×5.": "<b>Gas</b>: a bomb that hits it makes a 5×5 explosion.",
  "<b>Coffre bonus</b> : touche-le pour l'ouvrir. Toujours des pièces, parfois plus.": "<b>Bonus chest</b>: tap it to open it. Always coins, sometimes more.",
  "<b>Rythme</b> : tous les 10 niveaux, un niveau trésor rempli de minerai et de tas de pièces. Tous les 100 niveaux, un niveau gardien avec une grosse récompense.": "<b>Rhythm</b>: every 10 levels, a treasure level full of ore and coin piles. Every 100 levels, a guardian level with a big reward.",
  "<b>Géodes</b> : blanche (Common), rose (Rare), dorée (Epic), cristal (Legendary). Ouvre-les à l'atelier : chacune donne une gemme de sa rareté. Les gemmes ne se trouvent que dans les géodes.": "<b>Geodes</b>: white (Common), pink (Rare), golden (Epic), crystal (Legendary). Open them at the workshop: each gives a gem of its rarity. Gems are only found inside geodes.",

  /* ---------- Minerais et géodes ---------- */
  "Fer": "Iron",
  "Cuivre": "Copper",
  "Or": "Gold",
  "Mithril": "Mithril",
  "Cristal brut": "Raw crystal",
  "Géode blanche": "White geode",
  "Géode rose": "Pink geode",
  "Géode dorée": "Golden geode",
  "Géode cristal": "Crystal geode",
  "Agate bleue": "Blue agate",
  "Citrine": "Citrine",
  "Cristal turquoise": "Turquoise crystal",
  "Cristal de feu": "Fire crystal",
  "Quartz rose": "Rose quartz",

  /* ================================================================
     TEXTES DE config.js
     ================================================================ */

  /* ---------- Sac ---------- */
  "Sac plein : doublon laissé": "Bag full: duplicate left behind",

  /* ---------- Biomes ---------- */
  "Mine des pionniers": "Pioneers' Mine",
  "Cavernes de cristal": "Crystal Caverns",
  "Rivière souterraine": "Underground River",
  "Cœur volcanique": "Volcanic Heart",
  "Grottes obscures": "Dark Caves",
  "Forêt pétrifiée": "Petrified Forest",
  "Glacier profond": "Deep Glacier",
  "Abysses": "Abyss",
  "Cité engloutie": "Sunken City",
  "Trône du Roi Mineur": "Throne of the Miner King",

  /* ---------- Tutoriels ---------- */
  "Touche la pierre pour la casser": "Tap the stone to break it",
  "Casse le minerai de cuivre": "Break the copper ore",
  "Glisse pour dégager la géode": "Swipe to uncover the geode",
  "Arrose le magma": "Water the magma",
  "Casse le minerai de fer": "Break the iron ore",
  "Touche une case pour exploser": "Tap a cell to blow it up",
  "La pierre dure demande plus de coups": "Hard stone takes more hits",
  "Creuse la source": "Dig the spring",
  "Arrose une case : tout refroidit": "Water one cell: everything cools",
  "Creuse la case mystère": "Dig the mystery cell",
  "Casse la souche": "Break the stump",
  "Creuse la glace près du magma": "Dig the ice next to the magma",
  "Fais exploser le gaz": "Blow up the gas",
  "Touche le coffre": "Tap the chest",
  "Glisse pour creuser": "Swipe to dig",
  "Touche le trésor pour le ramasser": "Tap the treasure to pick it up",
  "Sac plein ! Remonte au village": "Bag full! Go back to the village",
  "Ouvre ton sac": "Open your bag",
  "Utilise la bombe": "Use the bomb",
  "Prends la pelle": "Take the shovel",
  "Prends la pioche": "Take the pickaxe",
  "Prends l'arrosoir": "Take the watering can",

  /* ---------- Niveaux spéciaux ---------- */
  "Niveau trésor ! Des tas de pièces et du minerai à ramasser.": "Treasure level! Piles of coins and ore to collect.",
  "Niveau gardien ! Un peu plus de roche dure… et une grosse récompense à la fin.": "Guardian level! A bit more hard rock… and a big reward at the end.",
  "La salle du trésor du Roi Mineur ! Le grand coffre du centre s'ouvre avec les 5 Clés du Roi Mineur.": "The Miner King's treasure room! The big chest in the middle opens with the 5 Miner King's Keys.",
  "Le trésor du Roi Mineur est à toi !": "The Miner King's treasure is yours!",

  /* ---------- Collections : gemmes ---------- */
  "Gemmes claires": "Clear gems",
  "Quartz": "Quartz",
  "Aigue-marine": "Aquamarine",
  "Topaze bleue": "Blue topaz",
  "Diamant brut": "Rough diamond",
  "Gemmes roses": "Pink gems",
  "Rhodochrosite": "Rhodochrosite",
  "Kunzite": "Kunzite",
  "Saphir rose": "Pink sapphire",
  "Gemmes dorées": "Golden gems",
  "Ambre": "Amber",
  "Topaze impériale": "Imperial topaz",
  "Héliodore": "Heliodor",
  "Gemmes royales": "Royal gems",
  "Rubis": "Ruby",
  "Émeraude": "Emerald",
  "Saphir étoilé": "Star sapphire",
  "Diamant pur": "Pure diamond",

  /* ---------- Collections : artefacts ---------- */
  "Fossiles de surface": "Surface fossils",
  "Coquillage fossile": "Fossil shell",
  "Feuille fossile": "Fossil leaf",
  "Petite ammonite": "Small ammonite",
  "Cartes célestes": "Star charts",
  "Plaque du Lion": "Lion plaque",
  "Plaque du Taureau": "Bull plaque",
  "Plaque du Scorpion": "Scorpion plaque",
  "Plaque du Dragon": "Dragon plaque",
  "Outils du mineur oublié": "Forgotten miner's tools",
  "Lampe rouillée": "Rusty lamp",
  "Vieille gourde": "Old flask",
  "Casque cabossé": "Dented helmet",
  "Pioche du premier mineur": "First miner's pickaxe",
  "Tablette ancienne": "Ancient tablet",
  "« Sous la montagne dort le trésor du Roi Mineur. Cinq clés, cachées de plus en plus profond, ouvrent son coffre. »": "“Beneath the mountain sleeps the Miner King's treasure. Five keys, hidden deeper and deeper, open his chest.”",
  "Fragment gauche": "Left fragment",
  "Fragment central": "Central fragment",
  "Fragment droit": "Right fragment",
  "Pierres de feu": "Fire stones",
  "Obsidienne": "Obsidian",
  "Pierre de lave": "Lava stone",
  "Cœur de braise": "Ember heart",
  "Trésors des abysses": "Treasures of the abyss",
  "Corail pétrifié": "Petrified coral",
  "Conque abyssale": "Abyssal conch",
  "Perle noire": "Black pearl",
  "Monnaies du royaume perdu": "Coins of the lost kingdom",
  "Sou de cuivre": "Copper penny",
  "Denier d'argent": "Silver denier",
  "Écu de bronze": "Bronze crown",
  "Ducat d'or": "Gold ducat",
  "Florin de platine": "Platinum florin",
  "Pièce du roi": "King's coin",
  "Reliques ornées": "Ornate relics",
  "Calice orné": "Ornate chalice",
  "Masque d'or": "Golden mask",
  "Sceptre du roi mineur": "Miner King's sceptre",
  "Clés du Roi Mineur": "Miner King's Keys",
  "Coffre du roi ouvert !": "King's chest unlocked!",
  "Clé de fer": "Iron key",
  "Clé de cuivre": "Copper key",
  "Clé d'argent": "Silver key",
  "Clé d'or": "Gold key",
  "Clé de cristal": "Crystal key",

  /* ---------- Objectifs du village ---------- */
  "Creuse {n} cases de terre": "Dig {n} dirt cells",
  "Trouve {n} trésors": "Find {n} treasures",
  "Termine {n} niveaux": "Complete {n} levels",
  "Atteins le niveau {n}": "Reach level {n}",
  "Casse {n} pierres": "Break {n} stones",
  "Récolte {n} minerais": "Gather {n} ores",
  "Achète une amélioration à la Forge": "Buy an upgrade at the Forge",
  "Ouvre {n} géodes": "Open {n} geodes",
  "Refroidis {n} cases de magma": "Cool {n} magma cells",
  "Utilise {n} bombes": "Use {n} bombs",
  "Complète une collection": "Complete a collection",
  "Plus d'énergie ! Retour au village avec ton butin.": "Out of energy! Back to the village with your loot.",
};
