/* =====================================================================
   MINE AUX TRÉSORS — TEXTES EN ANGLAIS
   ---------------------------------------------------------------------
   Quand le joueur choisit « English » dans les Paramètres, chaque texte
   français (à gauche) est remplacé par sa version anglaise (à droite).

   Quelques règles :
   - Ne change que le texte de DROITE (l'anglais).
   - Si tu modifies un texte français dans config.js (un nom de trésor,
     un tutoriel…), modifie aussi la ligne de gauche ici, sinon le jeu
     affichera le texte en français même en anglais.
   - Les {n}, {x}, {a}… sont remplacés par un nombre ou un nom :
     garde-les tels quels dans la traduction.
   - Garde les guillemets " " et la virgule à la fin de chaque ligne.
   ===================================================================== */
window.TEXTES_EN = {

  /* ---------- Titre, village, bâtiments ---------- */
  "Mine aux Trésors": "Treasure Mine",
  "Mine": "Mine",
  "Musée": "Museum",
  "Boutique": "Shop",
  "Forge": "Forge",
  "Atelier": "Workshop",
  "Améliorations": "Upgrades",
  "Articles": "Items",
  "Nouveau": "New",
  "Nouveau !": "New!",
  "Objectifs": "Goals",
  "La mine": "The mine",
  "Descendre": "Go down",
  "Descendre dans la mine": "Go down into the mine",
  "Entrée de la mine": "Mine entrance",
  "‹ Village": "‹ Village",
  "Record : niveau {n}": "Record: level {n}",
  "{n} checkpoint": "{n} checkpoint",
  "{n} checkpoints": "{n} checkpoints",
  "{a} / {b} trésors": "{a} / {b} treasures",
  "{n} géode": "{n} geode",
  "{n} géodes": "{n} geodes",
  "Aucune géode": "No geodes",
  "Pièces": "Coins",
  "pièces": "coins",
  "énergie": "energy",

  /* ---------- Paramètres ---------- */
  "Paramètres": "Settings",
  "Son": "Sound",
  "Musique": "Music",
  "Cheats": "Cheats",
  "Cheats débloqués": "Cheats unlocked",
  "Langue": "Language",
  "Français": "Français",
  "English": "English",
  "Comment jouer": "How to play",
  "Recommencer la partie": "Restart the game",
  "Confirmer : tout effacer ?": "Confirm: erase everything?",
  "Nouvelle partie !": "New game!",
  "Fermer": "Close",

  /* ---------- Objectifs ---------- */
  "Récupérer {n} pièces": "Collect {n} coins",
  "Objectif réussi : +{n} pièces !": "Goal complete: +{n} coins!",

  /* ---------- Mine : écran ---------- */
  "Niveau": "Level",
  "Niveau spécial": "Special level",
  "Niveau {n} ↓": "Level {n} ↓",
  "Niveau suivant ↓": "Next level ↓",
  "Mine suivante ↓": "Next mine ↓",
  "Énergie": "Energy",
  "Énergie pleine": "Energy full",
  "+1 dans {s} s": "+1 in {s} s",
  "Recharge au village": "Refills at the village",
  "Remonter au village": "Back to the village",
  "Trésors": "Treasures",
  "Trésors à trouver": "Treasures to find",
  "0 / 0 trouvés": "0 / 0 found",
  "{f} / {n} dégagés": "{f} / {n} uncovered",
  "Ouvrir le sac": "Open the bag",
  "Sac 0/4": "Bag 0/4",
  "Sac {n}/{cap}": "Bag {n}/{cap}",
  "Outils": "Tools",
  "Pelle": "Shovel",
  "Pioche": "Pickaxe",
  "Arrosoir": "Watering can",
  "Touche une case pour poser la bombe": "Tap a cell to place the bomb",
  "Annuler": "Cancel",
  "Gemme": "Gem",
  "Géode": "Geode",
  "Artefact": "Artefact",
  "{x} cachée": "Hidden {x}",
  "{x} (laissé)": "{x} (left behind)",

  /* ---------- Mine : messages ---------- */
  "Attention, c'est brûlant ! Refroidis le magma avec l'arrosoir.": "Careful, it's burning hot! Cool the magma with the watering can.",
  "Racine trop dure pour la pelle : casse sa souche à la pioche !": "This root is too tough for the shovel: break its stump with the pickaxe!",
  "La glace ne fond à la pelle que si elle touche du magma.": "Ice only melts with the shovel when it touches magma.",
  "La pelle ne passe pas la roche. Prends la pioche.": "The shovel can't get through rock. Take the pickaxe.",
  "La terre part à la pelle, et c'est gratuit !": "Dirt comes off with the shovel, and it's free!",
  "Trop chaud ! Arrose le magma pour le refroidir d'abord.": "Too hot! Water the magma to cool it first.",
  "Plus d'énergie ! +1 dans {s} s, ou bois une potion.": "Out of energy! +1 in {s} s, or drink a potion.",
  "Plus d'énergie ! Bois une potion ou remonte au village pour recharger.": "Out of energy! Drink a potion or go back to the village to refill.",
  "Plus de bombes ! Achètes-en à la boutique du village.": "No bombs left! Buy some at the village shop.",
  "Déjà refroidi : casse-le à la pioche.": "Already cooled: break it with the pickaxe.",
  "L'arrosoir sert à refroidir le magma.": "The watering can is for cooling magma.",
  "L'arrosoir se remplit… encore {s} s": "The watering can is refilling… {s} s left",
  "Chaîne ×{n} !": "Chain ×{n}!",
  "+{n} pièces": "+{n} coins",
  "+1 potion": "+1 potion",
  "+{n} potion": "+{n} potion",
  "+{n} potions": "+{n} potions",
  "Éclat !": "Shatter!",
  "Explosion de gaz !": "Gas explosion!",
  "La bombe ne vient pas à bout du magma chaud : arrose-le d'abord.": "Bombs can't clear hot magma: water it first.",
  "Il faut les {need} Clés du Roi Mineur pour ouvrir ce coffre (tu en as {got}). C'est un bonus : tu peux continuer sans !": "You need the {need} Miner King's Keys to open this chest (you have {got}). It's a bonus: you can carry on without it!",
  "Gardien vaincu !": "Guardian defeated!",
  "(à l'Atelier)": "(at the Workshop)",
  "Checkpoint niveau {n} débloqué !": "Checkpoint level {n} unlocked!",
  "⛺ Camp de biome débloqué (niveau {n}) !": "⛺ Biome camp unlocked (level {n})!",

  /* ---------- Descendre ---------- */
  "Sac plein, peu d'énergie": "Full bag, low energy",
  "Sac plein": "Full bag",
  "Peu d'énergie": "Low energy",
  "Attention, ton sac est plein et il te reste peu d'énergie.": "Careful, your bag is full and you're low on energy.",
  "Attention, ton sac est plein : tu ne pourras plus récupérer de trésors.": "Careful, your bag is full: you won't be able to pick up more treasures.",
  "Attention, il te reste peu d'énergie : remonte au village pour recharger.": "Careful, you're low on energy: go back to the village to recharge.",
  "Attention, il te reste peu d'énergie.": "Careful, you're low on energy.",
  "Remonter": "Go back up",
  "Descendre quand même": "Go down anyway",
  "Rester ici": "Stay here",

  /* ---------- Sac ---------- */
  "Mon sac": "My bag",
  "Consommables": "Consumables",
  "Retour à la mine": "Back to the mine",
  "{n} / {cap} cases utilisées": "{n} / {cap} slots used",
  "{n} place libre": "{n} free slot",
  "{n} places libres": "{n} free slots",
  "sac plein": "bag full",
  "Ton sac est vide pour l'instant.": "Your bag is empty for now.",
  "Minerais récoltés (hors sac) :": "Ores gathered (outside the bag):",
  "Utiliser": "Use",
  "Aucun consommable pour l'instant.": "No consumables yet.",
  "Nouvelle découverte !": "New discovery!",
  "Trésor trouvé": "Treasure found",
  "Ton sac est plein ({n} cases). Laisse un doublon de ton sac pour prendre cette nouvelle découverte ?": "Your bag is full ({n} slots). Leave a duplicate from your bag to take this new discovery?",
  "Ton sac est plein ({n} cases). Laisse un objet de ton sac pour prendre cette nouvelle découverte ?": "Your bag is full ({n} slots). Leave an item from your bag to take this new discovery?",
  "Laisser {x}": "Leave {x}",
  "doublon · et prendre le nouveau": "duplicate · and take the new one",
  "objet le moins précieux · et prendre le nouveau": "least valuable item · and take the new one",
  "Laisser la découverte": "Leave the discovery",
  "{x} laissé dans la mine": "{x} left in the mine",

  /* ---------- Consommables (sac et boutique) ---------- */
  "Bombe": "Bomb",
  "Fait sauter les 9 cases autour de la case touchée.": "Blows up the 9 cells around the cell you tap.",
  "Fait sauter les 9 cases autour de la cible.": "Blows up the 9 cells around the target.",
  "Radar": "Radar",
  "Entoure l'emplacement d'un trésor caché.": "Circles where a hidden treasure lies.",
  "Potion d'énergie": "Energy potion",
  "Remplit ton énergie au maximum.": "Fills your energy to the max.",
  "Pas de radar. Achètes-en à la boutique du village.": "No radar. Buy some at the village shop.",
  "Tous les trésors restants sont déjà repérés.": "All remaining treasures are already spotted.",
  "Radar : artefact repéré !": "Radar: artefact spotted!",
  "Radar : géode repérée !": "Radar: geode spotted!",
  "Pas de potion. Achètes-en à la boutique du village.": "No potion. Buy some at the village shop.",
  "Ton énergie est déjà pleine.": "Your energy is already full.",
  "Énergie rechargée !": "Energy refilled!",

  /* ---------- Boutique ---------- */
  "De l'équipement et des consommables pour tes descentes, payés en pièces.": "Gear and consumables for your trips down, paid in coins.",
  "Agrandir le sac": "Bigger bag",
  "{a} → {b} cases": "{a} → {b} slots",
  "{a} cases": "{a} slots",
  "Agrandir": "Upgrade",
  "Acheter": "Buy",
  "Sac agrandi : {n} cases !": "Bag upgraded: {n} slots!",

  /* ---------- Forge ---------- */
  "Améliore tes outils avec tes minerais et quelques pièces. Les améliorations sont permanentes.": "Improve your tools with your ores and a few coins. Upgrades are permanent.",
  "Réserve d'énergie": "Energy reserve",
  "Énergie max {a} → {b}": "Max energy {a} → {b}",
  "Énergie max {a}": "Max energy {a}",
  "Pioche renforcée": "Stronger pickaxe",
  "{a} → {b} dégâts par coup": "{a} → {b} damage per hit",
  "{a} dégâts par coup": "{a} damage per hit",
  "Coup en éclats": "Shattering blow",
  "Chance de casser aussi une roche voisine : {a} → {b}": "Chance to also break a nearby rock: {a} → {b}",
  "{a} de chance de casser une roche voisine": "{a} chance to break a nearby rock",
  "Arrosoir rapide": "Fast watering can",
  "Recharge {a} s → {b} s": "Refill {a} s → {b} s",
  "Recharge en {a} s": "Refills in {a} s",
  "Grand arrosoir": "Big watering can",
  "{a} → {b} arrosages avant de recharger": "{a} → {b} waterings before refilling",
  "{a} arrosages avant de recharger": "{a} waterings before refilling",
  "Un nouveau niveau se débloque plus profond": "A new level unlocks deeper down",
  "pour l'instant": "for now",
  "Forger": "Forge",
  "{x} : niveau {n} !": "{x}: level {n}!",

  /* ---------- Ascenseur ---------- */
  "Ascenseur": "Lift",
  "Choisis d'abord un biome. Ton record : niveau {n}.": "First choose a biome. Your record: level {n}.",
  "Choisis ton niveau de départ. Ton record : niveau {n}.": "Choose your starting level. Your record: level {n}.",
  "Niveaux {a}–{b}": "Levels {a}–{b}",
  "Niveau {n}": "Level {n}",
  "Descendre au niveau {n}": "Go down to level {n}",
  "Camp de biome": "Biome camp",
  "En cours": "In progress",
  "← Choisir un autre biome": "← Choose another biome",
  "Biome {n}": "Biome {n}",

  /* ---------- Retour à la surface ---------- */
  "Retour à la surface": "Back to the surface",
  "Fin de l'expédition": "End of expedition",
  "Niveau atteint : {n}": "Level reached: {n}",
  "Nouveau checkpoint !": "New checkpoint!",
  "Ouvrir les géodes": "Open geodes",
  "Minerais": "Ores",
  "Géodes": "Geodes",
  "Ton butin du niveau {n}": "Your loot from level {n}",
  "Tu remontes les mains vides cette fois. Ton niveau t'attend !": "You're coming back empty-handed this time. Your level is waiting for you!",
  "Ouvrir mes géodes à l'atelier": "Open my geodes at the workshop",
  "Aller au village": "Go to the village",
  "Vendu": "Sold",
  "Doublon": "Duplicate",
  "À ouvrir à l'atelier": "To open at the workshop",
  "Ajouté à ta collection": "Added to your collection",
  "{x} : nouvelle étoile !": "{x}: new star!",
  "Prime à récupérer au Musée": "Bonus to collect at the Museum",
  "{x} réunies !": "{x} complete!",
  "Aucun minerai récolté pour l'instant.": "No ores gathered yet.",

  /* ---------- Musée ---------- */
  "{a} trésors sur {b} sont exposés. Chaque nouveau trésor rapporte une prime, les doublons sont vendus à leur valeur. Complète une collection pour gagner une étoile : chaque étoile augmente le prix de revente de ses doublons.": "{a} of {b} treasures are on display. Each new treasure earns a bonus, duplicates are sold for their value. Complete a collection to earn a star: each star raises the resale price of its duplicates.",
  "Gemmes": "Gems",
  "Artefacts": "Artefacts",
  "{x} : +{n} pièces !": "{x}: +{n} coins!",
  "Prix de vente d'un doublon": "Resale price of a duplicate",
  "trouvé ×{n}": "found ×{n}",
  "Prochaine étoile : encore {n} objet": "Next star: {n} more item",
  "Prochaine étoile : encore {n} objets": "Next star: {n} more items",
  "prime {n} pièces": "bonus {n} coins",
  "Toutes les étoiles obtenues !": "All stars earned!",
  "doublon : {n} pièces": "duplicate: {n} coins",
  "Pas encore trouvé": "Not found yet",
  "Complète encore la collection pour gagner {n} pièces": "Complete the collection again to earn {n} coins",
  "Dans les géodes": "Inside geodes",
  "Où :": "Where:",
  "dès le niveau {a}": "from level {a}",
  "niveaux {a} à {b}": "levels {a} to {b}",
  "niveau {a}": "level {a}",
  "dans la terre": "in the dirt",
  "sous la pierre": "under stone",
  "sous la pierre dure": "under hard stone",
  "sous le magma": "under magma",
  "dans les coffres bonus": "in bonus chests",
  "Nouvelle étoile !": "New star!",
  "Nouvelles étoiles !": "New stars!",
  "Récupérer": "Collect",
  "doublons +{n} %": "duplicates +{n}%",
  "{n} étoile sur {max}": "{n} star out of {max}",
  "{n} étoiles sur {max}": "{n} stars out of {max}",
  "{n} collection restante à découvrir": "{n} collection left to discover",
  "{n} collections restantes à découvrir": "{n} collections left to discover",

  /* ---------- Atelier ---------- */
  "Frapper": "Strike",
  "Aucune géode à ouvrir. Trouve-en dans la mine !": "No geodes to open. Find some in the mine!",
  "Ouvrir : {x}": "Open: {x}",
  "Géode {r}, résistance {n} sur 4": "{r} geode, toughness {n} out of 4",
  "Si tu perds tes {n} cœurs, la géode s'ouvre quand même, mais donne une gemme {a} au lieu de {b}.": "If you lose your {n} hearts, the geode still opens, but gives a {a} gem instead of {b}.",
  "Si tu perds tes {n} cœurs, la géode blanche s'effrite et ne donne que <b>{c} pièces</b>.": "If you lose your {n} hearts, the white geode crumbles and only gives <b>{c} coins</b>.",
  "Coups": "Hits",
  "{a} coup(s) réussi(s) sur {b}": "{a} successful hit(s) out of {b}",
  "{x} : {gem} !": "{x}: {gem}!",
  "Plus de cœurs : la {x} s'ouvre quand même, mais donne {gem}.": "Out of hearts: the {x} still opens, but gives {gem}.",
  "Plus de cœurs : la géode blanche s'effrite. Tu récupères {n} pièces.": "Out of hearts: the white geode crumbles. You get {n} coins.",
  "Géode ouverte !": "Geode opened!",
  "Raté…": "Missed…",
  "Géode suivante": "Next geode",
  "Retour au village": "Back to the village",

  /* ---------- Fin de la mine ---------- */
  "Mine 2 : bientôt disponible": "Mine 2: coming soon",
  "Bravo, tu as atteint le fond de la mine ! Une nouvelle mine t'attend… elle arrive bientôt.": "Well done, you reached the bottom of the mine! A new mine awaits you… coming soon.",

  /* ---------- Comment jouer ---------- */
  "<b>Pelle</b> : maintiens et glisse sur la terre pour la retirer. Elle ne coûte rien.": "<b>Shovel</b>: hold and swipe over dirt to clear it. It costs nothing.",
  "<b>Pioche</b> : touche la pierre pour la casser. Chaque coup coûte 1 énergie : pierre 3 coups, minerai 3, magma refroidi 5.": "<b>Pickaxe</b>: tap stone to break it. Each hit costs 1 energy: stone 3 hits, ore 3, cooled magma 5.",
  "<b>Arrosoir</b> : refroidit le magma. Il lui faut quelques secondes pour se remplir.": "<b>Watering can</b>: cools magma. It needs a few seconds to refill.",
  "<b>Bombe</b> : dans ton sac, onglet Consommables. Elle fait sauter les 9 cases autour de la cible, sauf le magma chaud.": "<b>Bomb</b>: in your bag, Consumables tab. It blows up the 9 cells around the target, except hot magma.",
  "<b>Radar</b> : dans ton sac, onglet Consommables. Il entoure l'emplacement d'un trésor caché.": "<b>Radar</b>: in your bag, Consumables tab. It circles where a hidden treasure lies.",
  "<b>Sac</b> : chaque trésor et chaque géode prend une case (les minerais ne comptent pas). Agrandis-le à la boutique.": "<b>Bag</b>: each treasure and each geode takes one slot (ores don't count). Make it bigger at the shop.",
  "<b>Ascenseur</b> : au village, « Descendre » te propose les checkpoints débloqués (niveau 10, 20, 30…), rangés par biome. C'est gratuit.": "<b>Lift</b>: in the village, “Go down” offers the checkpoints you unlocked (level 10, 20, 30…), sorted by biome. It's free.",
  "<b>Remonter</b> : quitte la mine quand tu veux. Ton sac se vide : les nouveaux trésors vont au musée, les doublons sont vendus.": "<b>Go back up</b>: leave the mine whenever you want. Your bag is emptied: new treasures go to the museum, duplicates are sold.",
  "<b>Musée</b> : chaque nouveau trésor rapporte une prime. Complète une collection pour gagner une étoile (jusqu'à {n}) : ses doublons se vendent plus cher, et la prime se récupère au Musée.": "<b>Museum</b>: each new treasure earns a bonus. Complete a collection to earn a star (up to {n}): its duplicates sell for more, and the bonus is collected at the Museum.",
  "<b>Boutique</b> : agrandis ton sac. D'autres articles arrivent plus profond.": "<b>Shop</b>: make your bag bigger. More items arrive deeper down.",
  "<b>Forge</b> : améliore tes outils avec du fer, du cuivre, de l'or et des pièces.": "<b>Forge</b>: improve your tools with iron, copper, gold and coins.",
  "<b>Pierre dure</b> : il faut deux fois plus de coups de pioche.": "<b>Hard stone</b>: takes twice as many pickaxe hits.",
  "<b>Source</b> : creuse-la à la pelle, son eau refroidit le magma collé à elle.": "<b>Spring</b>: dig it with the shovel, its water cools the magma touching it.",
  "<b>Magma en chaîne</b> : arrose une case, tout le magma collé refroidit.": "<b>Chain magma</b>: water one cell and all the connected magma cools down.",
  "<b>Case mystère</b> : toujours un cadeau (pièces, minerai, potion ou géode).": "<b>Mystery cell</b>: always a gift (coins, ore, potion or geode).",
  "<b>Racines</b> : casse la souche, toutes ses racines disparaissent.": "<b>Roots</b>: break the stump and all its roots disappear.",
  "<b>Glace</b> : la pioche y fait moitié moins de dégâts. Collée au magma, elle fond d'un coup de pelle. Une bombe la fait fondre aussi.": "<b>Ice</b>: the pickaxe does half damage on it. Next to magma, it melts with one stroke of the shovel. A bomb melts it too.",
  "<b>Gaz</b> : une bombe qui le touche fait une explosion 5×5.": "<b>Gas</b>: a bomb that hits it makes a 5×5 explosion.",
  "<b>Coffre bonus</b> : touche-le pour l'ouvrir. Toujours des pièces, parfois plus.": "<b>Bonus chest</b>: tap it to open it. Always coins, sometimes more.",
  "<b>Rythme</b> : tous les 10 niveaux, un niveau trésor rempli de minerai et de tas de pièces. Tous les 100 niveaux, un niveau gardien avec une grosse récompense.": "<b>Rhythm</b>: every 10 levels, a treasure level full of ore and coin piles. Every 100 levels, a guardian level with a big reward.",
  "<b>Géodes</b> : blanche (Common), rose (Rare), dorée (Epic), cristal (Legendary). Ouvre-les à l'atelier : chacune donne une gemme de sa rareté. Les gemmes ne se trouvent que dans les géodes.": "<b>Geodes</b>: white (Common), pink (Rare), golden (Epic), crystal (Legendary). Open them at the workshop: each gives a gem of its rarity. Gems are only found inside geodes.",

  /* ---------- Minerais et géodes ---------- */
  "Fer": "Iron",
  "Cuivre": "Copper",
  "Or": "Gold",
  "Mithril": "Mithril",
  "Cristal brut": "Raw crystal",
  "Géode blanche": "White geode",
  "Géode rose": "Pink geode",
  "Géode dorée": "Golden geode",
  "Géode cristal": "Crystal geode",
  "Agate bleue": "Blue agate",
  "Citrine": "Citrine",
  "Cristal turquoise": "Turquoise crystal",
  "Cristal de feu": "Fire crystal",
  "Quartz rose": "Rose quartz",

  /* ================================================================
     TEXTES DE config.js
     ================================================================ */

  /* ---------- Sac ---------- */
  "Sac plein : doublon laissé": "Bag full: duplicate left behind",

  /* ---------- Biomes ---------- */
  "Mine des pionniers": "Pioneers' Mine",
  "Cavernes de cristal": "Crystal Caverns",
  "Rivière souterraine": "Underground River",
  "Cœur volcanique": "Volcanic Heart",
  "Grottes obscures": "Dark Caves",
  "Forêt pétrifiée": "Petrified Forest",
  "Glacier profond": "Deep Glacier",
  "Abysses": "Abyss",
  "Cité engloutie": "Sunken City",
  "Trône du Roi Mineur": "Throne of the Miner King",

  /* ---------- Tutoriels ---------- */
  "Touche la pierre pour la casser": "Tap the stone to break it",
  "Casse le minerai de cuivre": "Break the copper ore",
  "Glisse pour dégager la géode": "Swipe to uncover the geode",
  "Arrose le magma": "Water the magma",
  "Casse le minerai de fer": "Break the iron ore",
  "Touche une case pour exploser": "Tap a cell to blow it up",
  "La pierre dure demande plus de coups": "Hard stone takes more hits",
  "Creuse la source": "Dig the spring",
  "Arrose une case : tout refroidit": "Water one cell: everything cools",
  "Creuse la case mystère": "Dig the mystery cell",
  "Casse la souche": "Break the stump",
  "Creuse la glace près du magma": "Dig the ice next to the magma",
  "Fais exploser le gaz": "Blow up the gas",
  "Touche le coffre": "Tap the chest",
  "Glisse pour creuser": "Swipe to dig",
  "Touche le trésor pour le ramasser": "Tap the treasure to pick it up",
  "Sac plein ! Remonte au village": "Bag full! Go back to the village",
  "Ouvre ton sac": "Open your bag",
  "Utilise la bombe": "Use the bomb",
  "Prends la pelle": "Take the shovel",
  "Prends la pioche": "Take the pickaxe",
  "Prends l'arrosoir": "Take the watering can",

  /* ---------- Niveaux spéciaux ---------- */
  "Niveau trésor ! Des tas de pièces et du minerai à ramasser.": "Treasure level! Piles of coins and ore to collect.",
  "Niveau gardien ! Un peu plus de roche dure… et une grosse récompense à la fin.": "Guardian level! A bit more hard rock… and a big reward at the end.",
  "La salle du trésor du Roi Mineur ! Le grand coffre du centre s'ouvre avec les 5 Clés du Roi Mineur.": "The Miner King's treasure room! The big chest in the middle opens with the 5 Miner King's Keys.",
  "Le trésor du Roi Mineur est à toi !": "The Miner King's treasure is yours!",

  /* ---------- Collections : gemmes ---------- */
  "Gemmes claires": "Clear gems",
  "Quartz": "Quartz",
  "Aigue-marine": "Aquamarine",
  "Topaze bleue": "Blue topaz",
  "Diamant brut": "Rough diamond",
  "Gemmes roses": "Pink gems",
  "Rhodochrosite": "Rhodochrosite",
  "Kunzite": "Kunzite",
  "Saphir rose": "Pink sapphire",
  "Gemmes dorées": "Golden gems",
  "Ambre": "Amber",
  "Topaze impériale": "Imperial topaz",
  "Héliodore": "Heliodor",
  "Gemmes royales": "Royal gems",
  "Rubis": "Ruby",
  "Émeraude": "Emerald",
  "Saphir étoilé": "Star sapphire",
  "Diamant pur": "Pure diamond",

  /* ---------- Collections : artefacts ---------- */
  "Fossiles de surface": "Surface fossils",
  "Coquillage fossile": "Fossil shell",
  "Feuille fossile": "Fossil leaf",
  "Petite ammonite": "Small ammonite",
  "Cartes célestes": "Star charts",
  "Plaque du Lion": "Lion plaque",
  "Plaque du Taureau": "Bull plaque",
  "Plaque du Scorpion": "Scorpion plaque",
  "Plaque du Dragon": "Dragon plaque",
  "Outils du mineur oublié": "Forgotten miner's tools",
  "Lampe rouillée": "Rusty lamp",
  "Vieille gourde": "Old flask",
  "Casque cabossé": "Dented helmet",
  "Pioche du premier mineur": "First miner's pickaxe",
  "Tablette ancienne": "Ancient tablet",
  "« Sous la montagne dort le trésor du Roi Mineur. Cinq clés, cachées de plus en plus profond, ouvrent son coffre. »": "“Beneath the mountain sleeps the Miner King's treasure. Five keys, hidden deeper and deeper, open his chest.”",
  "Fragment gauche": "Left fragment",
  "Fragment central": "Central fragment",
  "Fragment droit": "Right fragment",
  "Pierres de feu": "Fire stones",
  "Obsidienne": "Obsidian",
  "Pierre de lave": "Lava stone",
  "Cœur de braise": "Ember heart",
  "Trésors des abysses": "Treasures of the abyss",
  "Corail pétrifié": "Petrified coral",
  "Conque abyssale": "Abyssal conch",
  "Perle noire": "Black pearl",
  "Monnaies du royaume perdu": "Coins of the lost kingdom",
  "Sou de cuivre": "Copper penny",
  "Denier d'argent": "Silver denier",
  "Écu de bronze": "Bronze crown",
  "Ducat d'or": "Gold ducat",
  "Florin de platine": "Platinum florin",
  "Pièce du roi": "King's coin",
  "Reliques ornées": "Ornate relics",
  "Calice orné": "Ornate chalice",
  "Masque d'or": "Golden mask",
  "Sceptre du roi mineur": "Miner King's sceptre",
  "Clés du Roi Mineur": "Miner King's Keys",
  "Coffre du roi ouvert !": "King's chest unlocked!",
  "Clé de fer": "Iron key",
  "Clé de cuivre": "Copper key",
  "Clé d'argent": "Silver key",
  "Clé d'or": "Gold key",
  "Clé de cristal": "Crystal key",

  /* ---------- Objectifs du village ---------- */
  "Creuse {n} cases de terre": "Dig {n} dirt cells",
  "Trouve {n} trésors": "Find {n} treasures",
  "Termine {n} niveaux": "Complete {n} levels",
  "Atteins le niveau {n}": "Reach level {n}",
  "Casse {n} pierres": "Break {n} stones",
  "Récolte {n} minerais": "Gather {n} ores",
  "Achète une amélioration à la Forge": "Buy an upgrade at the Forge",
  "Ouvre {n} géodes": "Open {n} geodes",
  "Refroidis {n} cases de magma": "Cool {n} magma cells",
  "Utilise {n} bombes": "Use {n} bombs",
  "Complète une collection": "Complete a collection",
  "Plus d'énergie ! Retour au village avec ton butin.": "Out of energy! Back to the village with your loot.",
  "Touche la terre pour creuser": "Tap the dirt to dig",
  "poche à géodes {a} / {b}": "geode pocket {a} / {b}",
  "poche à géodes {b}": "geode pocket {b}",
  "Poche à géodes : {a} → {b} géodes sans prendre de case": "Geode pocket: {a} → {b} geodes that take no slot",
  "Poche à géodes : {n} géodes sans prendre de case !": "Geode pocket: {n} geodes take no slot!",
  "Sac": "Bag",
  "Les checkpoints t'évitent de tout refaire": "Checkpoints save you from starting over",
  /* Premiers pas (niveaux 1 à 16) */
  "Tes trésors vont dans ton sac": "Your treasures go in your bag",
  "Descends au niveau suivant": "Go down to the next level",
  "Chaque coup de pioche coûte 1 énergie": "Each pickaxe hit costs 1 energy",
  "Continue jusqu'au checkpoint !": "Keep going to the checkpoint!",
  "Garde ta nouvelle découverte": "Keep your new discovery",
  "Remonte : du nouveau au village !": "Go back up: something new in the village!",
  "Le cuivre sert à améliorer ta pioche": "Copper is used to upgrade your pickaxe",
  "Tape quand le curseur est dans la zone": "Tap when the cursor is in the zone",
  "Agrandis ton sac à la Boutique": "Get a bigger bag at the Shop",
  "Une case de plus dans ton sac !": "One more slot in your bag!",
  "Tes objectifs rapportent des pièces": "Your goals earn you coins",
  "Bravo, tu connais la mine ! Bonne chance !": "Well done, you know the mine! Good luck!",
  "Énergie offerte pour ce tutoriel": "Free energy for this tutorial",
  "Bonus : hors du sac": "Bonus: not in the bag",
  "Ton sac est plein, mais tu peux continuer : les pièces et les minerais ne prennent pas de place.": "Your bag is full, but you can keep going: coins and ores don't take any space.",
  "Prochain checkpoint : niveau {n} (dans {k} niveau)": "Next checkpoint: level {n} ({k} level away)",
  "Prochain checkpoint : niveau {n} (dans {k} niveaux)": "Next checkpoint: level {n} ({k} levels away)",
  "Touche pour continuer": "Tap to continue",
  "Casse le magma refroidi": "Break the cooled magma",
  "Rentre au village avec ton butin": "Head home with your loot",
  "Descends dans la mine": "Go down into the mine",
  "Entre dans ton Musée": "Enter your Museum",
  "Entre dans la Forge": "Enter the Forge",
  "Entre dans l'Atelier": "Enter the Workshop",
  "Entre dans la Boutique": "Enter the Shop",
  "Récupère ta récompense": "Claim your reward",
  "Retourne au village": "Back to the village",
  "Redescends dans la mine": "Go back down the mine",
  "Reprends au niveau {n}": "Continue from level {n}",
  "Poche à géodes : 1 géode sans prendre de case": "Geode pocket: 1 geode takes no slot",
  "Poche à géodes : {n} géode sans prendre de case !": "Geode pocket: {n} geode takes no slot!",
  "Poche cousue": "Sewn pocket",
  "Poche à géodes": "Geode pocket",
  "Sac renforcé": "Reinforced bag",
  "Sac en cuir": "Leather bag",
  "Grande poche à géodes": "Large geode pocket",
  "Sac de mineur": "Miner's bag",
  "Sac à soufflets": "Expanding bag",
  "Poche à géodes doublée": "Double geode pocket",
  "Sac d'explorateur": "Explorer's bag",
  "Sac d'expédition": "Expedition bag",
  "Sac des profondeurs": "Bag of the depths",
  "Coffret à géodes": "Geode case",
  "Sac de cristal": "Crystal bag",
  "Sac royal": "Royal bag",
  "Sac du Roi Mineur": "Miner King's bag",

  /* ---------- Barre de navigation et écran Personnage ---------- */
  "Navigation": "Navigation",
  "Premium": "Premium",
  "Monde": "World",
  "Personnage": "Character",
  "Événements": "Events",
  "Bientôt": "Soon",
  "Le Musée s'ouvre à ton premier retour de la mine.": "The Museum opens when you first come back from the mine.",
  "Équipement": "Equipment",
  "Niv. {n}": "Lv. {n}",
  "Retire la terre d'un simple glissement": "Clears dirt with a simple swipe",
  "Toujours gratuite : aucune énergie dépensée": "Always free: no energy spent",
  "Sac de départ": "Starter bag",
  "Rechargée à chaque retour au village": "Refilled each time you go back to the village",
  "Niveau maximum atteint": "Maximum level reached",
  "Agrandir à la Boutique": "Upgrade at the Shop",
  "Améliorer à la Forge": "Upgrade at the Forge",
  "La Boutique arrive bientôt au village.": "The Shop will soon open in the village.",
  "La Forge arrive bientôt au village.": "The Forge will soon open in the village.",
  "Pas encore découvert : continue de descendre !": "Not discovered yet: keep going down!",

  /* ---------- Boutique premium et Événements ---------- */
  "Boutique premium": "Premium shop",
  "Les achats arrivent bientôt. Voici un aperçu de ce qui t'attend !": "Purchases are coming soon. Here's a preview of what's in store!",
  "Offre spéciale": "Special offer",
  "Pack de départ": "Starter pack",
  "Tout ce qu'il faut pour bien commencer l'aventure.": "Everything you need to get your adventure off to a great start.",
  "Poignée de pièces": "Handful of coins",
  "Bourse de pièces": "Purse of coins",
  "Coffre de pièces": "Chest of coins",
  "Avantages": "Perks",
  "Pass du mineur": "Miner's pass",
  "Des récompenses en plus à chaque palier de niveaux.": "Extra rewards at every level milestone.",
  "Des événements limités dans le temps, avec des récompenses spéciales. Le premier arrive bientôt !": "Limited-time events with special rewards. The first one is coming soon!",
  "Prochain événement": "Next event",
  "Ruée vers l'or": "Gold rush",
  "Pendant un week-end, plus d'or et plus de tas de pièces dans la mine.": "For one weekend, more gold and more coin piles in the mine.",
  "À venir": "Coming up",
  "Chasse aux fossiles": "Fossil hunt",
  "Trouve un maximum de fossiles pour gagner des récompenses.": "Find as many fossils as you can to earn rewards.",
  "Festival des géodes": "Geode festival",
  "Des géodes plus rares, à ouvrir à l'Atelier.": "Rarer geodes to open at the Workshop.",
  "Bientôt disponible !": "Coming soon!",

  /* ---------- Équipement, coffres et Forge ---------- */
  "Coffres": "Chests",
  "Améliore et fusionne ton équipement.": "Upgrade and merge your equipment.",
  "Ouvre des coffres pour trouver de l'équipement.": "Open chests to find equipment.",
  "Des articles pour tes descentes, payés en pièces.": "Items for your trips down, paid in coins.",
  "Publicité (simulée)": "Ad (simulated)",
  "Ton coffre arrive…": "Your chest is on its way…",
  "gemmes": "gems",
  "Bottes": "Boots",
  "Casque": "Helmet",
  "Gants": "Gloves",
  "Lanterne": "Lantern",
  "Pic lourd": "Heavy Pick",
  "Pic à éclats": "Shatter Pick",
  "Pic de givre": "Frost Pick",
  "Pelle de prospecteur": "Prospector's Shovel",
  "Pelle large": "Wide Shovel",
  "Gants de fer": "Iron Gloves",
  "Gants de dynamiteur": "Blaster Gloves",
  "Casque de chantier": "Hard Hat",
  "Casque de veine": "Vein Helmet",
  "Lanterne de prospecteur": "Prospector's Lantern",
  "Lanterne ancienne": "Ancient Lantern",
  "Bottes de prospecteur": "Prospector's Boots",
  "Bottes porte-bonheur": "Lucky Boots",
  "Commun": "Common",
  "Rare": "Rare",
  "Épique": "Epic",
  "Légendaire": "Legendary",
  "Mythique": "Mythic",
  "+{v} dégâts par coup": "+{v} damage per hit",
  "+{v} de pièces par tas": "+{v} coins per pile",
  "{v} de chance de +1 minerai par bloc": "{v} chance of +1 ore per block",
  "{v} de chance de coup gratuit (sans énergie)": "{v} chance of a free hit (no energy)",
  "Géodes rares {v} plus fréquentes": "Rare geodes {v} more frequent",
  "{v} de chance qu'une case de terre cache un tas d'or": "{v} chance that a dirt tile hides a gold pile",
  "{v} de chance de frapper deux fois plus fort": "{v} chance to hit twice as hard",
  "{v} de chance de casser aussi une roche voisine": "{v} chance to also break a nearby rock",
  "Dégâts sur la glace × {v} (au lieu de moitié)": "Damage on ice × {v} (instead of half)",
  "+{v} tas de pièces sur les niveaux trésor": "+{v} coin piles on treasure levels",
  "{v} de chance de creuser aussi une terre voisine": "{v} chance to also dig a nearby dirt tile",
  "{v} de chance de trouver aussi le meilleur minerai": "{v} chance to also find the best ore",
  "{v} de chance qu'une bombe ne soit pas utilisée": "{v} chance that a bomb is not used up",
  "Un coup gratuit casse le bloc d'un coup : {v} de chance": "A free hit breaks the block at once: {v} chance",
  "+{v} de chance de coup gratuit sur le minerai": "+{v} chance of a free hit on ore",
  "{v} de chance qu'une géode monte d'une rareté": "{v} chance that a geode goes up one rarity",
  "Artefacts jamais trouvés × {v} plus fréquents": "Never-found artefacts × {v} more frequent",
  "+{v} de tas d'or en plus": "+{v} more gold piles",
  "{v} de chance qu'un tas de pièces soit doublé": "{v} chance that a coin pile is doubled",
  "Coffre en bois": "Wooden chest",
  "Coffre d'argent": "Silver chest",
  "Coffre d'or": "Gold chest",
  "Coffre étoilé": "Star chest",
  "Clé en bois": "Wooden key",
  "Clé étoilée": "Star key",
  "Coffres d'équipement": "Equipment chests",
  "Ouvrir": "Open",
  "Il faut une clé": "Needs a key",
  "{r} garanti dans {n}": "{r} guaranteed in {n}",
  "Coffre du jour": "Daily chest",
  "Un coffre en bois gratuit chaque jour.": "A free wooden chest every day.",
  "Gratuit": "Free",
  "Offert !": "Free gift!",
  "Offert": "Free",
  "Revient dans": "Back in",
  "{h} h": "{h} h",
  "{m} min": "{m} min",
  "Coffre publicité": "Ad chest",
  "Regarde une publicité pour un coffre en bois (simulée dans le prototype).": "Watch an ad for a wooden chest (simulated in the prototype).",
  "Regarder": "Watch",
  "Le prix monte à chaque achat ({n}/{m} aujourd'hui).": "The price goes up with each purchase ({n}/{m} today).",
  "Les chances de chaque rareté sont affichées sur chaque coffre.": "The odds of each rarity are shown on every chest.",
  "Pas assez de gemmes.": "Not enough gems.",
  "+{n} {x}": "+{n} {x}",
  "+1 {x}": "+1 {x}",
  "Record niveau {n} !": "Record: level {n}!",
  "Ouvre {n} coffres": "Open {n} chests",
  "Touche pour ouvrir": "Tap to open",
  "Équiper": "Equip",
  "Remplacer": "Replace",
  "Ouvrir encore ({n})": "Open another ({n})",
  "Continuer": "Continue",
  "Fusion réussie !": "Merge successful!",
  "Niveau {n} / {m}": "Level {n} / {m}",
  "Niveau suivant : {x}": "Next level: {x}",
  "Passif du modèle (dès Épique)": "Model passive (from Epic)",
  "Retirer": "Unequip",
  "Améliorer": "Upgrade",
  "Niveau max": "Max level",
  "Fusionner avec": "Merge with",
  "Fusionner": "Merge",
  "Rareté maximale : cet objet ne peut plus fusionner.": "Highest rarity: this item can't be merged any more.",
  "Fusion : il faut {n} autres {x} {r} (tu en as {h}).": "Merge: you need {n} more {r} {x} (you have {h}).",
  "Fusion : il faut {n} autres objets {s} {r} (tu en as {h}).": "Merge: you need {n} more {r} {s} items (you have {h}).",
  "{x} équipé !": "{x} equipped!",
  "Tes bonus": "Your bonuses",
  "Rien d'équipé": "Nothing equipped",
  "Passifs actifs": "Active passives",
  "Énergie max {e} · Sac {b} cases · Dégâts de la pioche {d}": "Max energy {e} · Bag {b} slots · Pickaxe damage {d}",
  "Dégâts": "Damage",
  "Tous les bonus": "All bonuses",
  "Objets": "Items",
  "Les objets que tu trouves dans les coffres arrivent ici.": "Items you find in chests show up here.",
  "L'équipement arrive avec la Forge, au niveau {n}.": "Equipment arrives with the Forge, at level {n}.",
  "L'équipement arrive avec la Forge (niveau {n}).": "Equipment arrives with the Forge (level {n}).",
  "Se débloque au niveau {n}.": "Unlocks at level {n}.",
  "Trouve un objet {s} dans les coffres de la Boutique.": "Find a {s} in the Shop's chests.",
  "Fusion": "Merge",
  "Max": "Max",
  "Niv. {n} / {m}": "Lv. {n} / {m}",
  "Aller à la Boutique": "Go to the Shop",
  "Ouvre des coffres à la Boutique pour trouver ton premier équipement. Tu l'amélioreras ici avec des pièces et des minerais.": "Open chests at the Shop to find your first equipment. You'll upgrade it here with coins and ores.",
  "Améliore ton équipement avec des pièces et des minerais. Les autres objets s'améliorent depuis leur fiche.": "Upgrade your equipment with coins and ores. Other items are upgraded from their card.",
  "Fusion auto (Commun et Rare)": "Auto-merge (Common and Rare)",
  "Aucun objet pour l'instant.": "No items yet.",
  "Rien à fusionner automatiquement.": "Nothing to auto-merge.",
  "{n} fusions réussies !": "{n} merges done!",
  "En attendant l'Autel de la montagne, ces améliorations restent à la Forge.": "Until the Mountain altar arrives, these upgrades stay at the Forge.",
  "Améliore un objet à la Forge": "Upgrade an item at the Forge",
  "Coup gratuit !": "Free hit!",
  "Coup puissant !": "Power hit!",
  "Bombe gratuite !": "Free bomb!",
  "Tas d'or ! +{n}": "Gold pile! +{n}",
  "Ouvre ton coffre offert": "Open your free chest",
  "Touche le coffre !": "Tap the chest!",
  "Équipe ta nouvelle pioche": "Equip your new pickaxe",
  "Va voir ton équipement": "Go see your equipment",
  "Touche ta pioche": "Tap your pickaxe",
  "Améliore-la, c'est offert !": "Upgrade it, it's free!",
  "Fusionne 3 objets identiques": "Merge 3 identical items",
  "Épique S": "Epic S",
  "Légendaire S": "Legendary S",
  "3 objets identiques donnent 1 objet de la rareté au-dessus. Seule exception : Épique → Épique S accepte 2 autres Épiques du même emplacement. Ce que tu as dépensé pour les objets fusionnés t'est rendu.": "3 identical items make 1 item of the next rarity. One exception: Epic → Epic S accepts 2 other Epics of the same slot. What you spent on the merged items is given back.",
  "Ouvrir {n}": "Open {n}",
  "Pub": "Ad",
  "Ouvrir {n} × {x}": "Open {n} × {x}",
  "Il te manque {m} clé : {g} gemmes.": "You're missing {m} key: {g} gems.",
  "Il te manque {m} clés : {g} gemmes.": "You're missing {m} keys: {g} gems.",
  "Ta clé sera aussi utilisée.": "Your key will be used too.",
  "Tes {k} clés seront aussi utilisées.": "Your {k} keys will be used too.",
  "Tu as {g} gemmes.": "You have {g} gems.",
  "Il faut des clés pour ce coffre.": "This chest needs keys.",
  "Meilleur objet : {x}": "Best item: {x}",
  "Tous tes objets sont dans ton inventaire (onglet Personnage).": "All your items are in your inventory (Character tab).",
  "Ouvrir encore 10": "Open 10 more",
  "Confirmer": "Confirm",
  "Ouvrir des coffres": "Open chests",
  "Les articles arrivent plus profond dans la mine.": "Items arrive deeper in the mine.",
  // Player progression
  "Progression": "Progress",
  "Réussis des missions pour gagner de l'XP.": "Complete missions to earn XP.",
  "Objectif réussi : +{n} pièces, +{x} XP !": "Mission complete: +{n} coins, +{x} XP!",
  "Niveau {n} atteint ! Ta récompense t'attend dans Progression.": "Level {n} reached! Your reward is waiting in Progress.",
  "Débloque : {x}": "Unlocks: {x}",
  "Récupéré": "Claimed",
  "encore {n} XP": "{n} XP to go",
  "Récompense du niveau {n} récupérée !": "Level {n} reward claimed!",
  "Les Événements se débloquent au niveau {n} du joueur.": "Events unlock at player level {n}.",
  "Début de l'aventure": "Start of the adventure",
};
